2024-Fri-28 14:54:03 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
2024-Fri-28 14:54:46 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/1.1" 401 41 (connectionpool.py:547)
2024-Fri-28 14:54:46 [    INFO] [testsimpleBookApi.test03_Place_new_Order_ofBook] Placing order without token (test03_Place_new_Order_ofBook.py:63)
2024-Fri-28 14:54:46 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
2024-Fri-28 14:55:30 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /api-clients HTTP/1.1" 201 82 (connectionpool.py:547)
2024-Fri-28 14:55:30 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
2024-Fri-28 14:56:13 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/1.1" 400 38 (connectionpool.py:547)
2024-Fri-28 14:56:13 [    INFO] [testsimpleBookApi.test03_Place_new_Order_ofBook] Placing order with invalid user with token (test03_Place_new_Order_ofBook.py:75)
2024-Fri-28 14:56:13 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
2024-Fri-28 14:56:57 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/1.1" 400 38 (connectionpool.py:547)
2024-Fri-28 14:56:57 [    INFO] [testsimpleBookApi.test03_Place_new_Order_ofBook] placing order with valid user with token (test03_Place_new_Order_ofBook.py:23)
2024-Fri-28 14:56:57 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
